# This is a basic workflow to help you get started with Actions

name: TEST2

# Controls when the action will run. 
on: 
  push:
    branches: 
    - main
    paths:
    - 'sf/**'

jobs:
  notify:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - name: 'Send Notification'
        run: |
         echo ${{github.event}}
